[[redirects]]
from = "/"
  to = "https://pre-onboarding-selection-task.shop/"
  status = 200
  force = false
  signed = "REACT_APP_API_BASE_URL"

[[redirects]]
from = "/signup"
  to = "https://pre-onboarding-selection-task.shop/signup"
  status = 200
  force = false
  signed = "REACT_APP_API_BASE_URL"


